### ISSUE TITLE
Suppoert other forms of wake locks 

### ISSUE THREAD

**Issue by derolf** [creativecreatorormaybenot/wakelock#68] opened 2020-12-12 23:14 UTC
Proximity wake lock would be nice

**Comment by creativecreatorormaybenot** [comment] 2020-12-12 23:25
Hi @derolf :) Thanks for opening this issue 👌

Could you elaborate on this? This might be a duplicate of #1.

**Comment by creativecreatorormaybenot** [comment] 2020-12-12 23:28
(my reasoning for closing CPU wakelocks on Android was that you would write Android code anyway when that would be useful, so no benefit to include it in the plugin)

**Comment by creativecreatorormaybenot** [comment] 2021-01-07 13:37
I realize that proximity wakelock is something different than in #1, however, it is something entirely different than what we wakelock currently does. I feel like it might not fit with the existing API, however, feel free to contribute any ideas 👍

**Closed** 2021-01-07 13:36 UTC
Labels: requires further investigation, waiting for response
