### ISSUE TITLE
wrong Kotlin version?

### ISSUE THREAD

**Issue by fehernyul** [creativecreatorormaybenot/wakelock#169] opened 2022-02-07 09:24 UTC
\.pub-cache\hosted\pub.dartlang.org\wakelock-0.6.1]()+1\android\src\main\kotlin\creativemaybeno\wakelock\Wakelock.kt: (23, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is **1.5.1**, expected version is **1.1.15.**

**Comment by creativecreatorormaybenot** [comment] 2022-02-07 10:38
Duplicate of #162

**Closed by creativecreatorormaybenot** 2022-02-07 10:38 UTC
