### ISSUE TITLE
Error while using the plugin.

### ISSUE THREAD

**Issue by kphanipavan** [creativecreatorormaybenot/wakelock#54] opened 2020-10-28 13:40 UTC
Unable to complete build process after importing wakelock.dart file in my flutter application.

![](https://cdn.discordapp.com/attachments/745288827740094615/770994272967065630/Screenshot_2020-10-28_at_6.25.45_PM.png)

The error is shown as above.
A build for MacOS is working fine.
It is just with Android.
Haven't tested with iOS.

**Comment by creativecreatorormaybenot** [comment] 2020-10-28 17:27
Thanks for opening the issue! 😃

Are you sure that this only happens with wakelock?

**Comment by erkanmrs** [comment] 2020-10-28 23:07
same issue, 
```
Launching lib\main.dart on MI 8 in debug mode...
lib\main.dart:1
Plugin project :import_js_library not found. Please update settings.gradle.
```

when i remove  below lines from  wakelock pubspec.yaml warning gone

```
      web:
        default_package: wakelock_web
```

**Comment by creativecreatorormaybenot** [comment] 2020-10-28 23:17
@erkanmrs No, that is not an issue - you can check #49. You can safely ignore the warning :)

**Comment by kphanipavan** [comment] 2020-10-29 01:35
No, I haven't tested any other plugins yet

**Comment by creativecreatorormaybenot** [comment] 2020-10-29 01:37
@kphanipavan It does not look like this is an issue with `wakelock`. This is why it would be important to know if you still experience the issue when you remove the `wakelock` dependency.

**Comment by anthonyorona** [comment] 2020-10-29 19:13
@creativecreatorormaybenot I have checked other plugins, this only happens with wakelock.

Launching lib/main.dart on SM A716U1 in debug mode...
Running Gradle task 'assembleDebug'...
Plugin project :import_js_library not found. Please update settings.gradle.
✓ Built build/app/outputs/flutter-apk/app-debug.apk.

**Comment by creativecreatorormaybenot** [comment] 2020-10-29 21:22
@anthonyorona This is a warning that you can safely ignore - see #48.

Do you have any problems with the `wakelock` plugin itself?

**Comment by creativecreatorormaybenot** [comment] 2020-10-29 21:32
I assume that this is a:

Duplicate of #48 

Let me know if I am wrong.

**Comment by creativecreatorormaybenot** [comment] 2020-10-29 21:33
Duplicate of #48.

**Comment by creativecreatorormaybenot** [comment] 2020-10-29 21:33
Duplicates #48

**Comment by creativecreatorormaybenot** [comment] 2020-10-29 21:33
Duplicate of #48

**Closed by creativecreatorormaybenot** 2020-10-29 21:32 UTC
Labels: bug, requires further investigation, waiting for response

**Comment by creativecreatorormaybenot** [comment] 2020-11-08 05:09
The issue has been fixed :) Running `flutter pub upgrade` will do the trick.
