### ISSUE TITLE
'Flutter/Flutter.h' file not found on Flutter 2.0.1

### ISSUE THREAD

**Issue by nizwar** [creativecreatorormaybenot/wakelock#95] opened 2021-03-05 16:11 UTC
My project is not ready for nullsafety, and still use wakelock-0.2.1+1, its generate following error while running the application

`1 error generated.
    /Library/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.2.1+1/ios/Classes/messages.m:4:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~`

its only happened with latest flutter version (2.0.1), when i downgrade it to 1.22.6, its working really fine, is there any ways to solve this?

Flutter doctor result : 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.0)
[✓] Connected device (4 available)

**Comment by creativecreatorormaybenot** [comment] 2021-03-05 16:33
Hi @nizwar :) Thanks for opening the issue!

You can now already use the latest wakelock version when you have not migrated to null safety yet.

I would suggest bumping to the latest version and running `flutter clean`. Hope it helps 🙂

**Comment by creativecreatorormaybenot** [comment] 2021-03-06 19:23
I think that there is nothing to do from the wakelock side of things, hence, closing for now. Let me know if this should be reopened :)

**Comment by psrcek** [comment] 2021-03-08 14:33
This happens with wakelock 0.5.0+2 aswell
Happens only on iOS. Compiles on android just fine.

```
> Compiling wakelock-dummy.m
> Compiling messages.m

[x] /Users/buildmachine/flutter/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.0+2/ios/Classes/messages.m:4:9: 'Flutter/Flutter.h' file not found

#import <Flutter/Flutter.h>
        ^~~~~~~~~~~~~~~~~~~


> Compiling wakelock_vers.c
> Compiling WakelockPlugin.m
```

dart: `2.12.0`
flutter: `2.0.1`

**Comment by creativecreatorormaybenot** [comment] 2021-03-08 16:05
@psrcek Have you tried running `flutter clean`?

I am not sure why this would suddenly appear. This code has not been touched.

**Comment by psrcek** [comment] 2021-03-08 16:17
Our CI runs flutter clean before each build, so.. yes.

**Comment by creativecreatorormaybenot** [comment] 2021-03-08 16:29
@psrcek Can you reproduce this with a newly created project? (`flutter create bug`)

Otherwise, this is probably faulty Podfile configuration.

**Comment by ekuleshov** [comment] 2021-03-08 17:34
Have the same issue and `flutter clean` didn't resolve it.

Is it suggested to recreate the ios project and podfile somehow?

**Comment by creativecreatorormaybenot** [comment] 2021-03-08 18:14
@ekuleshov I am not sure - do you think you can look into it?

I bet this is a simple config change necessary, however, I have no idea to be honest.

**Comment by ekuleshov** [comment] 2021-03-08 18:29
@creativecreatorormaybenot I'm not really sure what to look at. Downgrading Flutter to 1.x resolved issue for the time being.

Quick search found things like this https://github.com/flutter/flutter/issues/70895 though recommended workarounds with clean ore removing podfile.lock didn't help here. I'd have to try this again when I'll have some more time.

**Comment by creativecreatorormaybenot** [comment] 2021-03-08 18:37
@ekuleshov Thanks for investigating.

I will also keep this in my mind to see if I can tackle this asap.

**Comment by creativecreatorormaybenot** [comment] 2021-03-11 02:50
If anyone has insights on this, please let me know :) I am glad to accept any contributions!

**Comment by psrcek** [comment] 2021-03-11 09:38
I was able to fix the issue with [this](https://github.com/flutter/flutter/issues/70895#issuecomment-792755327) suggestion.
I just added the line `flutter_additional_ios_build_settings(target)` in the `post_install do` decleration in our Podfile.

**Comment by creativecreatorormaybenot** [comment] 2021-03-11 09:57
Thanks a lot @psrcek 🙏 

Are you suggesting that [this fix](https://github.com/flutter/flutter/issues/70895#issuecomment-792755327) has to be done in **your app** or in the **wakelock plugin**? :)

**Comment by psrcek** [comment] 2021-03-11 10:01
No idea if that should be fixed in wakelock or in the end user app, but fixing it in my app worked for me. Since this seems like a required config migration to flutter 2.0.0 I think it might be a required fix in the app. I haven't tried creating a new app, but my best guess is that line already exists in newly created apps in flutter >=2.0.0.

**Closed** 2021-06-29 13:06 UTC
Labels: bug, p0, requires further investigation

**Comment by LiangLuDev** [comment] 2021-12-01 15:40
> I was able to fix the issue with [this](https://github.com/flutter/flutter/issues/70895#issuecomment-792755327) suggestion. I just added the line `flutter_additional_ios_build_settings(target)` in the `post_install do` decleration in our Podfile.

thanks . Solved using this solution
