### ISSUE TITLE
wakelock not working on iOS 13

### ISSUE THREAD

**Issue by SdxCoder** [creativecreatorormaybenot/wakelock#121] opened 2021-06-29 05:36 UTC
Its working properly on android but not on iOS. What I do is when a song is playing in my application I  call `Wakelock.enable`. And when its stopped by user I call `Wakelock.disable`. But its not working for iPhone devices. Tested on iOS 13.

**Comment by creativecreatorormaybenot** [comment] 2021-06-29 13:05
Might be a duplicate of #29 - did you check that?

**Closed** 2021-07-27 16:08 UTC

**Comment by LeeNgocTus** [comment] 2022-07-26 08:10
I have the same problem like this on IOS, on android no problem. I have a switch to set to allow the screen to stay on all the time and turn it off. When the switch state is ON, I call the function Wakelock.enable to keep the screen always on on my app. When the Switch state is OFF, I call the Wakelock.disable function to turn the function off. But the problem is that when I switch my Switch state to OFF, the screen stays on all the time. On an android device I ran and didn't get this error. 
Sorry for my English not good.
