### ISSUE TITLE
wakelock not working on Flutter-Web-Safari

### ISSUE THREAD

**Issue by NgYewChun** [creativecreatorormaybenot/wakelock#117] opened 2021-06-10 02:54 UTC
for Flutter Web ,  it works well on android (chrome) , but not working on iPhone safari, screen goes off after around 30 seconds.
all I do is simply call Wakelock.enable() in widget void initState() as below

void initState() {

super.initState();  
 Wakelock.enable();

}

version wakelock: ^0.5.2

**Comment by creativecreatorormaybenot** [comment] 2021-06-10 02:56
Hi, that is indeed possible. Safari has notoriously bad compatibility.

We are already using a polyfill, but it might not support all browsers. You could contribute by checking that.

**Comment by creativecreatorormaybenot** [comment] 2021-09-14 01:07
I will close this for now since this is either not actually an issue, not confirmed to be not working yet, or a compatibility issue that cannot be resolved from the plugin-side.

Might need to open a new issue once browser compatibility advances.

**Closed by creativecreatorormaybenot** 2021-09-14 01:07 UTC
