### ISSUE TITLE
iOS 13.4.1 goes always in standby

### ISSUE THREAD

**Issue by maerlynflagg** [creativecreatorormaybenot/wakelock#29] opened 2020-05-14 08:17 UTC
i tried this ones to keep awake a iOS device (iOS 13.4.1 , iPhone 11 Pro Max):
```
      await Wakelock.enable();
      await Wakelock.toggle(on: true);
```
every function called without an catched error, but no matter, which function, always go the device in black screen (standby).

is this a bug in the plugin. when the functions are called on iOS 13.4.1 devices?

i know for some weeks, the plugin works fine on iOS and the device skipped standby.

**Comment by creativecreatorormaybenot** [comment] 2020-05-14 08:38
Thank you for reporting the issue. 

Unfortunately, I do not have the ability to test on iOS at the moment. This means that I cannot really debug this 😕

Are you aware of any change in this iOS version? If you have an idea how to fix it, I will gladly accept any PR :+1:

**Comment by rlueders** [comment] 2020-06-08 14:27
I tested on my iphone 7 and this plugin successfully keeps the screen on past the expected timeout period.

**Comment by maerlynflagg** [comment] 2020-06-08 17:42
currently i observe it. my colleage's iphone still goes to standby , after call the function.

**Comment by creativecreatorormaybenot** [comment] 2020-06-08 21:38
@maerlynflagg I will be able to debug on iOS soon. If you can remind me in two weeks, I can check this.

In the meantime, if you have any idea why this might be happening, feel free to start a discussion and open a PR 🙂

**Comment by fyredave** [comment] 2020-06-22 18:34
@creativecreatorormaybenot I have a client reporting this issue when I archive the build and distribute via enterprise distribution. I also notice sometimes the local deployment doesn't work either. Usually need to clean and rebuild the app to restore it. No error logs, it just stops working and the phone will go to sleep as if it wasn't called. This is happening on my test device using iOS 12.4.1.

**Comment by ravish-tech** [comment] 2020-07-05 10:02
I can confirm that on ios 13.5.1 `Wakelock.enable()` works and my screen stays on. But after calling `Wakelock.disable()` (after user moves to another screen), my phone stays on.

**Comment by creativecreatorormaybenot** [comment] 2020-07-05 12:13
Does anyone have an idea why this might be happening?

**Comment by maerlynflagg** [comment] 2020-08-24 06:53
> Wakelock doesn't seem to be doing anything on 13.6.1 as far as I can tell.

oh thanks for info!

**Comment by deniza** [comment] 2020-08-27 15:03
Hey guys. I am using wakelock 0.1.4+2 on a live project and its working fine both on iOS 13.6.1 and 14.0 (latest beta).

**Comment by fyredave** [comment] 2020-08-31 21:53
Updating my previous comment, only saw an issue when building with xcode. When building with vscode it seemed to work fine.

**Comment by tnaseem** [comment] 2020-10-29 04:53
I just tried 0.1.4+2 myself, after your findings @deniza. However, the report I get back from my client is that it's still happening (iOS 13.5.1)

What's weird though is that they're saying it happens on some screens, but not others, but the code (with the Wavelock.enabled() in initState), is the same! I'd expect they either all work, or not at all.

Totally confused!

**Comment by creativecreatorormaybenot** [comment] 2020-10-29 05:08
@tnaseem You might be releasing the wakelock somewhere else.

I would advise you to enable the wakelock rather often to be sure that you have the correct state.  
If you really want to be sure, you could place it in a position listener for a video or potentially even the build method of an animation (although there should be better places).

**Comment by tnaseem** [comment] 2020-10-29 05:13
I'll give that a go. Thanks.

As an aside - I currently, I enable it in initState() and disable in dispose(). But will give your suggestion a go. I do have a positionBuilder running (audio, rather than video) for other aspects of the app, so this should be simple enough!

Question: Should I check for 'enabled' first? or just force it periodically with a Wakelock.enable()?

**Comment by creativecreatorormaybenot** [comment] 2020-10-29 05:44
@tnaseem You do not need to check for `enabled` because the plugin checks it for you :)

It is, in fact, more efficient to not check it yourself because you only need to communicate with the platform once.

**Comment by tnaseem** [comment] 2020-10-29 08:41
Your suggestion worked to keep it awake. Many thanks for the heads up! :)

Still no idea why it disables after I call `Wakelock.enable()`. Something, somewhere, is disabling it. I've even removed ALL `Wakelock.disable()` from my code to test and still it happens. Very strange.

Anyway, below is the workaround I've adopted. Listing here in case it's of use to anyone. It's a helper class, which uses a periodic timer to do the enable - Save as `keep_awake.dart` or something:

```
import 'dart:async';
import 'package:wakelock/wakelock.dart';

const Duration defaultInterval = Duration(seconds: 20);

class KeepAwake {

  static Timer _wakeTimer;

  static void start({Duration interval = defaultInterval}) {
    Wakelock.enable();

    _wakeTimer = Timer.periodic(interval, (_) {
      Wakelock.enable();
    });
  }

  static void stop() {
    Wakelock.disable();
    _wakeTimer.cancel();
  }
}
```

To start the periodic timer, just call the following in initState():
```
KeepAwake.start();
```

It defaults to running every 20 seconds, but you can override this with a Duration argument.

Don't forget to call:
```
KeepAwake.stop();
```
in your `dispose()` function, otherwise the timer will keep running!

Hope this helps!

**Comment by creativecreatorormaybenot** [comment] 2020-10-29 14:46
@tnaseem The system can also release the wakelock and I am glad you find a solution 👌

**Comment by creativecreatorormaybenot** [comment] 2020-10-29 14:47
I will close this for now as it seems that this is not really an issue with wakelock.

**Closed by creativecreatorormaybenot** 2020-10-29 14:47 UTC
Labels: bug, requires further investigation
