### ISSUE TITLE
Add an option to keep the cpu running too. 

### ISSUE THREAD

**Issue by AbdulSamadgithub** [creativecreatorormaybenot/wakelock#192] opened 2023-02-19 06:42 UTC
```dart
Wakelock.enableScreenOnly();
Wakelock.enableCpuOnly();
Wakelock.enableCpuAndScreen();

Wakelock.disableScreenOnly();
Wakelock.disableCpuOnly();
Wakelock.disableCpuAndScreen();
```
### [Wake lock](https://developer.android.com/reference/android/os/PowerManager.WakeLock#release())

**Comment by creativecreatorormaybenot** [comment] 2023-02-19 11:48
Duplicate of #30.

**Closed by creativecreatorormaybenot** 2023-02-19 11:48 UTC
