### ISSUE TITLE
regression: Plugin project :import_js_library not found.

### ISSUE THREAD

**Issue by llucax** [creativecreatorormaybenot/wakelock#49] opened 2020-10-13 08:48 UTC
After upgrading to 0.2.0+1 I'm getting this "error" (in quotes because it's shown in red but it doesn't actually prevents it from working) when running `flutter run` in my project:

```
Plugin project :import_js_library not found.
```

**Comment by creativecreatorormaybenot** [comment] 2020-10-13 08:59
Thanks for reporting the issue 👍

No need to worry about this 🙂 Duplicate of #48.

**Closed by creativecreatorormaybenot** 2020-10-13 08:59 UTC

**Comment by creativecreatorormaybenot** [comment] 2020-10-13 09:11
Duplicate of #48

**Comment by llucax** [comment] 2020-10-13 11:01
Woops! Sorry, I usually check if the issue was already reported, I guess I forgot this time :-/
