### ISSUE TITLE
Plugin project :import_js_library not found.

### ISSUE THREAD

**Issue by kaboc** [creativecreatorormaybenot/wakelock#48] opened 2020-10-06 02:36 UTC
I've seen the error message **"Plugin project :import_js_library not found. Please update settings.gradle."** in the console on every `flutter run` (on Windows, targeting an Android device) after I updated wakelock to 0.2.0+1. Despite the error, wakelock seems to be working fine.

Is there anything missing on the plugin side, or do I need additional configurations to run the app without the error?

**Comment by creativecreatorormaybenot** [comment] 2020-10-06 06:27
Thanks for reporting the issue - I think that this should not happen.

Steps for your:

* What is your Flutter version? (`flutter --version`)
* If it is outdated, please run `flutter upgrade`.
* Try to run `flutter clean` in your project.

**Comment by kaboc** [comment] 2020-10-06 12:24
- flutter --version
```
Flutter 1.22.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d408d302e2 (7 days ago) • 2020-09-29 11:49:17 -0700
Engine • revision 5babba6c4d
Tools • Dart 2.10.0
```

I ran `flutter clean` before trying each of wakelock 0.1.4+2 and 0.2.0+1. The error occurred only with 0.2.0+1.

I also created a new project with `wakelock: 0.2.0+1` added in pubspec.yaml, and it resulted in the same error.

**Comment by creativecreatorormaybenot** [comment] 2020-10-06 12:28
@kaboc Which version of `import_js_library` are you using?

Can you do `flutter pub deps`?

**Comment by kaboc** [comment] 2020-10-06 12:47
@creativecreatorormaybenot 
```
Dart SDK 2.10.0
Flutter SDK 1.22.0
wl 1.0.0+1
|-- cupertino_icons 1.0.0
|-- flutter 0.0.0
|   |-- characters 1.1.0-nullsafety.3
|   |-- collection 1.15.0-nullsafety.3
|   |-- meta 1.3.0-nullsafety.3
|   |-- sky_engine 0.0.99
|   |-- typed_data 1.3.0-nullsafety.3
|   |   '-- collection...
|   '-- vector_math 2.1.0-nullsafety.3
|-- flutter_test 0.0.0
|   |-- async 2.5.0-nullsafety.1
|   |   '-- collection...
|   |-- boolean_selector 2.1.0-nullsafety.1
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- characters...
|   |-- charcode 1.2.0-nullsafety.1
|   |-- clock 1.1.0-nullsafety.1
|   |-- collection...
|   |-- fake_async 1.2.0-nullsafety.1
|   |   |-- clock...
|   |   '-- collection...
|   |-- flutter...
|   |-- matcher 0.12.10-nullsafety.1
|   |   '-- stack_trace...
|   |-- meta...
|   |-- path 1.8.0-nullsafety.1
|   |-- source_span 1.8.0-nullsafety.2
|   |   |-- charcode...
|   |   |-- collection...
|   |   |-- path...
|   |   '-- term_glyph...
|   |-- stack_trace 1.10.0-nullsafety.1
|   |   '-- path...
|   |-- stream_channel 2.1.0-nullsafety.1
|   |   '-- async...
|   |-- string_scanner 1.1.0-nullsafety.1
|   |   |-- charcode...
|   |   '-- source_span...
|   |-- term_glyph 1.2.0-nullsafety.1
|   |-- test_api 0.2.19-nullsafety.2
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- collection...
|   |   |-- matcher...
|   |   |-- meta...
|   |   |-- path...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- string_scanner...
|   |   '-- term_glyph...
|   |-- typed_data...
|   '-- vector_math...
'-- wakelock 0.2.0+1
    |-- flutter...
    |-- meta...
    |-- wakelock_platform_interface 0.1.0
    |   |-- flutter...
    |   '-- meta...
    '-- wakelock_web 0.1.0+2
        |-- flutter...
        |-- flutter_web_plugins 0.0.0
        |   |-- characters...
        |   |-- collection...
        |   |-- flutter...
        |   |-- meta...
        |   |-- typed_data...
        |   '-- vector_math...
        |-- import_js_library 1.0.1
        |   |-- flutter...
        |   |-- flutter_web_plugins...
        |   |-- html 0.14.0+4
        |   |   |-- csslib 0.16.2
        |   |   |   '-- source_span...
        |   |   '-- source_span...
        |   '-- js...
        |-- js 0.6.2
        '-- wakelock_platform_interface...
```

I can see `import_js_library` is in the above result, but I haven't explicitly added it in pubspec.yaml. Do I have to add `import_js_library: ^1.0.1` or some related package as well as `wakelock: ^0.2.0+1`.

FYI, what I'm trying to do is not to run my app on the web, but I just want to run it as a mobile app on a smartphone.

**Comment by creativecreatorormaybenot** [comment] 2020-10-06 12:51
@kaboc No, `wakelock` is the only dependency you need.

The reason I asked is because this is really weird. I have not seen anyone else with this issue 🤔

Did you create your Android project with the latest `flutter create`? It seems like a Gradle issue, but there should not be one.

**Comment by creativecreatorormaybenot** [comment] 2020-10-06 12:53
(btw, `import_js_library` is included for web support, but it is not used on mobile. However, the dependency obviously always needs to be there)

**Comment by creativecreatorormaybenot** [comment] 2020-10-06 12:56
@kaboc Can you try running the example app? 

You should be able to find it like this: 

* Control click onto your `Wakelock.enable` (e.g.) call in Android Studio.
* Now, you should see the path to the wakelock file in your cache.
* Navigate there and open the `example` project in Android Studio.
* Try to run that project (`flutter pub get` & `flutter run`).

(If you are not using Android Studio, it should still be very similar - you can also clone the repo, but that might be cumbersome)

**Comment by kaboc** [comment] 2020-10-06 12:59
@creativecreatorormaybenot 
Yes, I used `flutter create`.

I'll try running the example app. I'm usually using Android Studio.

**Comment by kaboc** [comment] 2020-10-06 13:39
@creativecreatorormaybenot 
D:\tool\dev\flutter\.pub-cache\hosted\pub.dartlang.ort\wakelock-0.2.0+1\example

flutter pub get
```
Cannot open file, path = 'D:\tool\dev\flutter\.pub-cache\global_packages\wakelock_example\pubspec.lock' (OS Error: The system cannot find the file specified, errno = 3)
pub get failed (66; , errno = 3))
```

I have no idea why Flutter tried to open `pubspec.lock` in a different directory, but it failed anyway, so I copied the example folder to another place and managed to get it to run.

However, the same error was shown even with the example app.

I wonder if the above path issue has something to do with the error. I've started to suspect there is something wrong with my environment...
Let's see if anyone else experiences the issue for a while (for a week or a little longer, as the latest version was released just a few days ago, I think).

**Comment by creativecreatorormaybenot** [comment] 2020-10-06 13:40
@kaboc Thank you a lot already!

I hope someone else can reproduce this issue as well 👍

**Comment by creativecreatorormaybenot** [comment] 2020-10-07 00:36
@kaboc I have an update on this 🎉

I am confident to close this issue because:

1. It is not an issue with `wakelock` itself but with `import_js_library`. I have therefore created an issue on that repo: https://github.com/florent37/flutter_web_import_js_library/issues/3
1. I did not realize that this was not an actual build problem, i.e. it does not affect `wakelock` at all.

Thanks for reporting, though 👍

**Closed by creativecreatorormaybenot** 2020-10-07 00:36 UTC
Labels: requires further investigation, waiting for response

**Comment by kaboc** [comment] 2020-10-07 00:46
@creativecreatorormaybenot 
Sorry for having bothered you.
Thank you too!

**Comment by anthonyorona** [comment] 2020-10-29 19:15
Is there anything that can be done to prevent this warning from popping up with we are using Wakelock for mobile only?

**Comment by creativecreatorormaybenot** [comment] 2020-10-29 21:31
@anthonyorona You can upvote https://github.com/florent37/flutter_web_import_js_library/pull/4 (which is another plugin). 

The PR fixes it. If you really hate to see that warning (which you can just ignore), you can add a dependency override that uses the PR for the `import_js_library` dependeny.

**Comment by creativecreatorormaybenot** [comment] 2020-11-08 05:08
This has been fixed now :) You can run `flutter pub upgrade` for the fix.
